### PR TITLE
Fix sending messages when an attachment is not set

### PR DESCRIPTION
**Pull request by steve228uk**
### What?

Currently messages were not sending if an attachment was not set. This fixes that.

----

CC @hamchapman

### CODE REVIEW

**Comment by hamchapman** [comment]
Thanks for this! Looks like quite a large oversight on my part. Sorry about that!

I'll make sure that I add some tests for this on Monday so it can't happen in future.

**Comment by steve228uk** [comment]
@hamchapman Did you manage to look into getting some tests written for this? It would be great to have it merged if possible 😊

**Comment by hamchapman** [comment]
@steve228uk I did but got caught up in trying to get stubbing of a HTTP/2 streamed request working!

I think I'll merge this for now and follow up with the tests later once I've got the stubbing working properly. Thanks again!

**Comment by steve228uk** [comment]
@hamchapman You're a hero 😄 Thanks so much!

**Pull request merged**
